<?php

namespace ProcessWire;

use GraphQL\Type\Definition\Type;
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\InputObjectType;

class GraphQLFieldtypeCombo extends WireData implements Module {

	/**
	 * getModuleInfo is a module required by all modules to tell ProcessWire about them
	 * @return array
	 */
	public static function getModuleInfo() {

		return [
			'title' => 'GraphQLFieldtypeCombo',
			'version' => 1,
			'summary' => 'GraphQL support for FieldtypeCombo.',
			'icon' => 'globe',
			'requires' => ['FieldtypeCombo']
		];
	}

	public static function getType(Field $field) {

		$subfields = $field->getComboSettings()->getSubfields();
		
		$desc = $field->description;
      	if (!$desc) {
        	$desc = "Field with the type of {$field->type}.";
      	}

		return new ObjectType([
			'name' => $field->name,
			'description' => $desc,
			'fields' => self::getFields($subfields),
		]);
	}


	public static function getFields($subfields) {
    $fields = [];

    foreach ($subfields as $field) {
      $fieldClass = self::pwSubfieldToGraphqlClass($field);
      if (is_null($fieldClass)) {
        continue;
      }

	  //TODO check permissions

      $fieldSettings = $fieldClass::field($field);

      if ($field->required) {
        $fieldSettings['type'] = Type::nonNull($fieldSettings['type']);
      }

      $fields[] = $fieldSettings;

    }

    return $fields;
  }

  public static function pwSubfieldToGraphqlClass($subfield)
  {
    // use local field if available
    $className =
      "\\ProcessWire\\GraphQL\\Type\\Fieldtype\\Fieldtype" . $subfield->type;

    if (class_exists($className)) {
      return $className;
    }

    //TODO third party field

    return null;
  }

  	//TODO input type
	//TODO set value type
}